# Generated by Django 5.2.3 on 2025-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='شناسه کاربر')),
                ('access_token', models.TextField(verbose_name='توکن دسترسی')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'احراز هویت کاربر',
                'verbose_name_plural': 'احراز هویت کاربران',
            },
        ),
    ]
