# Generated by Django 5.2.3 on 2025-07-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khodroyar', '0002_conversation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ (ریال)')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='کد مرجع')),
                ('ref_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شماره پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='شروع اشتراک')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='پایان اشتراک')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khodroyar.userauth', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_auth', 'status'], name='khodroyar_p_user_au_38bde2_idx'), models.Index(fields=['status', 'created_at'], name='khodroyar_p_status_b44788_idx'), models.Index(fields=['authority'], name='khodroyar_p_authori_3213ed_idx')],
            },
        ),
    ]
