# Generated by Django 5.2.3 on 2025-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khodroyar', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='متادیتا'),
        ),
    ]
