"""
Django settings for data_line project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n_@)gy1)fmt7ozkv+ae$$&%4e=2wcb(d7ejtmqt2t=7yx&*wvc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['data-line.ir']

# CSRF settings
CSRF_TRUSTED_ORIGINS = ['https://data-line.ir']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'resumeyar',
    'ostadkar',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'data_line.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'data_line.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

OAUTH_APPS_SETTINGS = {
    "ostadkar": {
        "api_key": os.getenv('OSTADKAR_API_KEY'),
        "oauth_client_id": os.getenv('OSTADKAR_OAUTH_CLIENT_ID'),
        "oauth_client_secret": os.getenv('OSTADKAR_OAUTH_CLIENT_SECRET'),
        "oauth_redirect_uri": os.getenv('OSTADKAR_OAUTH_REDIRECT_URI'),
        "oauth_scope": os.getenv('OSTADKAR_OAUTH_SCOPE', 'USER_ID&'),
    },
    "resumeyar": {
        "api_key": os.getenv('RESUMEYAR_API_KEY', ''),
        "oauth_client_id": os.getenv('RESUMEYAR_OAUTH_CLIENT_ID', 'amber-foam-healer'),
        "oauth_client_secret": os.getenv('RESUMEYAR_OAUTH_CLIENT_SECRET', ''),
        "oauth_redirect_uri": os.getenv('RESUMEYAR_OAUTH_REDIRECT_URI', ''),
        "oauth_scope": os.getenv('RESUMEYAR_OAUTH_SCOPE', 'USER_ID'),
    }
}
                  
OAUTH_AUTHORIZATION_URL = 'https://oauth.divar.ir/oauth2/auth'
OAUTH_TOKEN_URL = 'https://oauth.divar.ir/oauth2/token'
OAUTH_USER_INFO_URL = 'https://open-api.divar.ir/v1/open-platform/users'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# S3 Storage Configuration (Media files only)
USE_S3 = os.getenv('USE_S3', 'False').lower() == 'true'

if USE_S3:
    # Add django-storages to INSTALLED_APPS
    if 'storages' not in INSTALLED_APPS:
        INSTALLED_APPS.append('storages')
    
    # AWS Settings
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    
    # S3 Media settings only (static files remain local)
    AWS_S3_MEDIA_LOCATION = 'media'
    DEFAULT_FILE_STORAGE = 'data_line.storage.MediaStorage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_S3_MEDIA_LOCATION}/'
    
    # S3 Settings
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False

# Login URL for @login_required
LOGIN_URL = '/ostadkar/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
