# Generated by Django 5.2.3 on 2025-07-07 15:01

import django.db.models.deletion
import ostadkar.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'تصویر پست', 'verbose_name_plural': 'تصاویر پست'},
        ),
        migrations.AlterModelOptions(
            name='samplework',
            options={'ordering': ['created_at'], 'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.AlterModelOptions(
            name='userauth',
            options={'verbose_name': 'احراز هویت کاربر', 'verbose_name_plural': 'احراز هویت کاربران'},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=ostadkar.models.sample_work_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='sample_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostadkar.samplework', verbose_name='نمونه کار'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='post_token',
            field=models.CharField(max_length=8, verbose_name='توکن پست'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostadkar.userauth', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه یکتا'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='access_token',
            field=models.TextField(verbose_name='توکن دسترسی'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='شناسه کاربر'),
        ),
    ]
