# Generated by Django 5.2.3 on 2025-06-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='samplework',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostadkar.userauth'),
        ),
    ]
