# Generated by Django 5.2.3 on 2025-07-09 13:29

import django.db.models.deletion
import ostadkar.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0003_alter_samplework_post_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=ostadkar.models.sample_work_image_path, verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ (ریال)')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد مرجع')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره پیگیری')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sample_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ostadkar.samplework', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
