# Generated by Django 5.2.3 on 2025-07-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0004_alter_postimage_image_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauth',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
    ]
