# Generated by Django 5.2.3 on 2025-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0006_postaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplework',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='بررسی شده'),
        ),
    ]
