# Generated by Django 5.2.3 on 2025-07-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ostadkar', '0008_add_archive_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='کد مرجع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شماره پیگیری'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='postaddon',
            name='addon_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='شناسه افزونه'),
        ),
        migrations.AlterField(
            model_name='postaddon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='postaddon',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('created', 'ایجاد شده'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='تاریخ آرشیو'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='آرشیو شده'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='بررسی شده'),
        ),
        migrations.AlterField(
            model_name='samplework',
            name='post_token',
            field=models.CharField(db_index=True, max_length=8, unique=True, verbose_name='توکن پست'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='شناسه کاربر'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sample_work', 'status'], name='ostadkar_pa_sample__de1e85_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='ostadkar_pa_status_a8501e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['authority'], name='ostadkar_pa_authori_35632d_idx'),
        ),
        migrations.AddIndex(
            model_name='postaddon',
            index=models.Index(fields=['sample_work', 'status'], name='ostadkar_po_sample__e76d66_idx'),
        ),
        migrations.AddIndex(
            model_name='postaddon',
            index=models.Index(fields=['status', 'created_at'], name='ostadkar_po_status_68e27b_idx'),
        ),
        migrations.AddIndex(
            model_name='samplework',
            index=models.Index(fields=['user', 'is_archived'], name='ostadkar_sa_user_id_0d6780_idx'),
        ),
        migrations.AddIndex(
            model_name='samplework',
            index=models.Index(fields=['is_reviewed', 'is_archived'], name='ostadkar_sa_is_revi_49e25f_idx'),
        ),
        migrations.AddIndex(
            model_name='samplework',
            index=models.Index(fields=['created_at', 'is_archived'], name='ostadkar_sa_created_28a665_idx'),
        ),
    ]
