# Generated by Django 5.2.3 on 2025-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemoonekar', '0002_alter_postimage_options_alter_samplework_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplework',
            name='post_token',
            field=models.CharField(max_length=8, unique=True, verbose_name='توکن پست'),
        ),
    ]
