# Generated by Django 5.2.3 on 2025-07-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemoonekar', '0005_userauth_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='مدت زمان (روز)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('created', 'ایجاد شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('addon_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه افزونه')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sample_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemoonekar.samplework', verbose_name='نمونه کار')),
            ],
            options={
                'verbose_name': 'افزونه پست',
                'verbose_name_plural': 'افزونه\u200cهای پست',
                'ordering': ['-created_at'],
            },
        ),
    ]
