# Generated by Django 5.2.3 on 2025-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemoonekar', '0009_add_database_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='nemoonekar__sample__087bc8_idx',
            old_name='nemoonekar_pa_sample__de1e85_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='nemoonekar__status_6c3201_idx',
            old_name='nemoonekar_pa_status_a8501e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='nemoonekar__authori_8606f5_idx',
            old_name='nemoonekar_pa_authori_35632d_idx',
        ),
        migrations.RenameIndex(
            model_name='postaddon',
            new_name='nemoonekar__sample__958aca_idx',
            old_name='nemoonekar_po_sample__e76d66_idx',
        ),
        migrations.RenameIndex(
            model_name='postaddon',
            new_name='nemoonekar__status_e590ad_idx',
            old_name='nemoonekar_po_status_68e27b_idx',
        ),
        migrations.RenameIndex(
            model_name='samplework',
            new_name='nemoonekar__user_id_736b7b_idx',
            old_name='nemoonekar_sa_user_id_0d6780_idx',
        ),
        migrations.RenameIndex(
            model_name='samplework',
            new_name='nemoonekar__is_revi_f89c6c_idx',
            old_name='nemoonekar_sa_is_revi_49e25f_idx',
        ),
        migrations.RenameIndex(
            model_name='samplework',
            new_name='nemoonekar__created_16baf3_idx',
            old_name='nemoonekar_sa_created_28a665_idx',
        ),
        migrations.AddField(
            model_name='samplework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
